### ISSUE TITLE
edwebcontroller:read-path-variables fails on single argument

### ISSUE THREAD

**Issue by Kolophonium0** [ediarum/ediarum.WEB#6] opened 2022-05-03 09:42 UTC
Im using ediarum.web 1.13. Here i get the Problem, that if i use the api to get something like:
`
api/<object-name>/<object-id>/<part-id>
`
where `<part-id>` is `P1`
the function above keeps returning
`<param key="Kapitel" value="1"/>`
I added a test for that. Heres the output:
`
<testcase name="read-path-variables" class="edwebcontroller:read-path-variables">
            <failure message="assertEquals failed." type="failure-error-code-1">&lt;param key='Kapitel' value='B1'/&gt;</failure>
            <output>
                <param key="Kapitel" value="1"/>
            </output>
        </testcase>
`
if i add 1 random character in front it works. I tried to solve it myself, but i cant get my head around why it works in the old version. Maybe its something that changed in eXist 5.3?

**Comment by Kolophonium0** [comment] 2022-05-03 17:08
I did a quick fix by changing:
`let $path-tail := if (fn:count($path-regex-parts) eq 1) then ($path) else (replace($path, "^"||string-join(for $p in subsequence($path-regex-parts, 1, $pos -1) return $p(1)), ""))`
Its not good but it doesnt seem to conflict with other functionality. Maybe @MartinFechner has a better idea?

**Comment by Kolophonium0** [comment] 2022-05-03 19:00
I fixed it for the moment by changing in edwebcontroller:read-path-variables:

**Comment by MartinFechner** [comment] 2022-06-07 11:47
Can you please give more information? I can't reproduce the error. The call `edwebcontroller:read-path-variables("/api/Kapitel/P1","/api/<object-type>/<object-id>", "[.@:\w\d]+")` gives as result:

```
<param key="object-type" value="Kapitel"/>
<param key="object-id" value="P1"/>
```

**Comment by Kolophonium0** [comment] 2022-06-07 21:14
Sure. The Problem persists with a call like: `'B1'` when slashes are absent. Im not really sure of today if this is linked to #3 but i think it was also the case with a fresh installation. I run into this Problem when i request an object part. edwebcontroller:read-path-variables then gets called with just the part-id as input which then cuts the first character of the input and returns the remaining chars.

**Comment by MartinFechner** [comment] 2022-08-02 11:43
Thanks for clarification. The call `edwebcontroller:read-path-variables("P1","/<object-id>", "[.@:\w\d]+")` does reproduce the error.  I think if you change the line

https://github.com/ediarum/ediarum.WEB/blob/62184f6386cc335c224c953e08733d04214aac25/content/edweb-controller.xql#L712

to 

```xquery
        let $path-tail := 
            if (count($path-regex-parts) = 1)
            then $path
            else replace ($path, "^"||string-join(for $p in subsequence($path-regex-parts, 1, $pos -1) return $p(1)), "")
```

the problem should be fixed. Can you please test this?

**Comment by Kolophonium0** [comment] 2023-03-07 19:37
Sorry for my late response. The code that you send me is basically the fix i added in my pull request am i correct? If so i tested it and it works and i encountered no side effects.

**Comment by MartinFechner** [comment] 2023-06-14 14:50
Is fixed with the last commit

**Closed by MartinFechner** 2023-06-14 14:50 UTC
